---
title: "KNN"
output: word_document
---

```{r}
library(FNN)
library(ggplot2)
library(plyr)
setwd("~/Documents/226Project")
train = read.csv(file = "final_train_data.csv")
validate = read.csv(file = "final_validation_data.csv")
train = train[,-1]
validate = validate[,-1]

stdize = function(df) {
  continuous_covariates = c("Model_Year", "Mileage", "Feedback_Perc", "N_Reviews", "review_polarity", "review_positivity")
  for(i in 1:length(continuous_covariates)) {
    x_bar = mean(df[,continuous_covariates[[i]]])
    scale = sd(df[,continuous_covariates[[i]]])
    df[,continuous_covariates[[i]]] = (df[,continuous_covariates[[i]]]-x_bar)/scale
  }
  return(df)
}

color_col = grep("^Exterior_Color$", colnames(train))
train = train[,-color_col]
validate = validate[,-color_col]
make_col = grep("^Make$", colnames(train))
train = train[,-make_col]
validate = validate[,-make_col]
type_col = grep("^Type$", colnames(train))
train = train[,-type_col]
validate = validate[,-type_col]
status_col = grep("^Seller_Status$", colnames(train))
train = train[,-status_col]
validate = validate[,-status_col]

cols <- sapply(train, is.logical)
train[,cols] <- lapply(train[,cols], as.numeric)
train

cols <- sapply(validate, is.logical)
validate[,cols] <- lapply(validate[,cols], as.numeric)
validate

train = stdize(train)
train_obs = train[-1]
validate = stdize(validate)
validate_obs = validate[-1]

train_obs
validate_obs

k = seq(1, 100, 1)
knn.rmse = rep(0, length(k))

for(i in 1:length(k)) {
  knn.fit = knn.reg(train_obs, validate_obs, train$Price, k[[i]])
  knn.errors = (validate$Price - knn.fit$pred)^2
  knn.rmse[[i]] = sqrt(mean(knn.errors))
}

k.best = which.min(knn.rmse)
k.best
knn.rmse[[k.best]]

df = data.frame(k, knn.rmse)

p = ggplot(data = df, aes(x = k, y = knn.rmse)) + geom_point(alpha = I(0.7))
p
```

```{r}
# Ranging over k and L, report accuracy
library(class)
knn.err = adply(seq(10,30,1), 1, function(K) {
  # Run KNN 
  knn.raw = knn(train = train_obs,
                test = validate_obs,
                cl = train$New,
                k = K, l = 0,
                use.all = TRUE,
                prob = TRUE)
  # Get the vote shares that the majority possessed
  knn.probs = aaply(1:length(knn.raw), 1, function(i) { 
    if (knn.raw[i] == TRUE) { return(attributes(knn.raw)$prob[i]) }
    else { return(1 - attributes(knn.raw)$prob[i]) }
  })
  # Compute the TP, FP, FN, TN from the model on the test data
  ROC = adply(seq(0,1.05,0.05), 1, function(thresh) {
    L = thresh*K/100
    knn.out = as.numeric(knn.probs >= thresh)
    TP = sum( validate$New * knn.out )
    FP = sum( (1 - validate$New) * knn.out )
    FN = sum( validate$New * (1 - knn.out) )
    TN = sum( (1 - validate$New) * (1 - knn.out) )
    df = data.frame(K, L, TP, FP, TN, FN, thresh)
    return(df)
  }, .id = NULL)
  
  return(ROC)
}, .id = NULL)
  
# Comput accuracy, TPR, FPR
knn.err$accuracy = (knn.err$TP + knn.err$TN)/nrow(validate)
knn.err$TPR = (knn.err$TP)/(knn.err$TP + knn.err$FN)
knn.err$FPR = (knn.err$FP)/(knn.err$FP + knn.err$TN)

knn.err$accuracy
knn.err$TPR
knn.err$TP/(knn.err$TP + knn.err$FP)
```

