---
title: "inference"
output: word_document
---

```{r}
#import train and test data and get ride of X1 column
library(ggplot2)
library(dplyr)
setwd("~/Year 3 - Autumn/MS&E 226/Project/Data")
train = read.csv(file = "final_train_data.csv")
test = read.csv(file = "final_test_data.csv")
train = train[,-1]
train = train[,-10]
test = test[,-1]
test = test[,-10]
```

```{r}
fm.lower = lm(data = train, Price ~ 1)
fm.upper = lm(data = train, Price ~ . + I(Model_Year^2) + I(Mileage^2))
stepped = step(fm.lower,
     scope = list(lower = fm.lower,
                  upper = fm.upper),
     direction = "forward")
stepwise_formula = formula(stepped)
```
```{r}
stepwise_model_train = lm(stepwise_formula, train)
#summary(stepwise_model_train)
X_train <- as.data.frame(summary(stepwise_model_train)$coefficients)
Y_train <- cbind(X_train[,c("Estimate", "Pr(>|t|)")])
sorted_coefficients_train <- Y_train[order(Y_train$`Pr(>|t|)`),]
sorted_coefficients_train_filtered <- subset(sorted_coefficients_train, `Pr(>|t|)` <= 0.05)
sorted_coefficients_train_filtered
```
#fit on test data

```{r}
stepwise_model = lm(stepwise_formula, test)
#summary(stepwise_model)
X <- as.data.frame(summary(stepwise_model)$coefficients)
Y <- cbind(X[,c("Estimate", "Pr(>|t|)")])
sorted_coefficients_test <- Y[order(Y$`Pr(>|t|)`),]
sorted_coefficients_test_filtered <- subset(sorted_coefficients_test, `Pr(>|t|)` <= 0.05)
sorted_coefficients_test_filtered
```
#model with all of the covariates
```{r}
complete_model = lm(data = train, Price ~ . + I(Model_Year^2) + I(Mileage^2))
summary(complete_model)
```



```{r}
library(matrixStats)
set.seed(2)
bstar = NULL
n = nrow(train)
B = 1000
for(i in 1:B) {
  Dstar = train[sample(1:nrow(train),size=nrow(train),replace=TRUE),]
  model = lm(stepwise_formula, Dstar)
  bstar = rbind(bstar, coef(model))
}
SEs = colSds(bstar)
bstar = data.frame(bstar)
lower_bound = colMeans(bstar) - 1.96*SEs 
upper_bound = colMeans(bstar) + 1.96*SEs 
intervals = data.frame(cbind(SEs, colMeans(bstar), lower_bound, upper_bound))
intervals
```
